---
variables:
  PROTOC_VERSION: 3.5.1
  APP_NAME: grpc-example
  CHART_REGISTRY_URI: ${REGISTRY_HOST}/${REGISTRY_ORG}/${REGISTRY_CHART_NAME}
  CI_REF: refs/heads/master
  EVENT: push
  FAILFASTCI_STATUS_API: https://failfast.ci.cnct.io//api/v1/github_status
  GITHUB_INSTALLATION_ID: 64807
  GITHUB_REPO: samsung-cnct/sample-grpc-apiserver
  HELM_REGISTRY_IMAGE: quay.io/samsung_cnct/helm-registry-agent
  HELM_REGISTRY_VERSION: v0.7.4-helm_2.6
  KUBECTL_VERSION: v1.8.5
  PR_ID: 
  REF_NAME: master
  REGISTRY_CHART_NAME: krakengrpc
  REGISTRY_HOST: quay.io
  REGISTRY_ORG: samsung_cnct
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  PROTOC_IMAGE: registry.cnct.io/common-tools/samsung-cnct_sample-grpc-apiserver/golang-protoc:latest

stages:
  - build
  - docker
  - helm
  - deploy
  - github-status-update

before_script:
  - export CHART_VER=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')
  - export CHART_REL=$(git rev-list --count v${CHART_VER}..HEAD 2>/dev/null )
  - mkdir -p /go/src/github.com/samsung-cnct
  - ln -s /common-tools/samsung-cnct_sample-grpc-apiserver /go/src/github.com/samsung-cnct/sample-grpc-apiserver
  - cd /go/src/github.com/samsung-cnct/sample-grpc-apiserver

build:
  stage: build
  image: $PROTOC_IMAGE
  artifacts:
    paths:
    - ${CHART_NAME}
  script:
#    - mkdir -p /go/src/github.com/samsung-cnct
#    - ln -s /common-tools/samsung-cnct_sample-grpc-apiserver /go/src/github.com/samsung-cnct/sample-grpc-apiserver
#    - cd /go/src/github.com/samsung-cnct/sample-grpc-apiserver
#    - pwd && echo $GOPATH && ls -al
    - ./bin/gen_apis.sh
    - go build -o rootfs/grpc_server/server ./server
    - go build -o rootfs/grpc_server/client ./client
  artifacts:
    untracked: true

unit-tests:
  stage: build
  image: $PROTOC_IMAGE
  script:
    - ./bin/checks/verify-gosimple.sh
    - ./bin/test.sh -v

generate_docs:
  stage: build
  image: $PROTOC_IMAGE
  script:
    - ./bin/gen_apis.sh
  artifacts:
    untracked: true
    paths: 
      - /common-tools/samsung-cnct_sample-grpc-apiserver/docs/*
    expire_in: 14 day

build_image:
  stage: docker
  image: docker:latest
    - docker:dind
  dependencies: 
    - build
  before_script:
    - docker info
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_HOST/$REGISTRY_ORG
  script:
    - docker build -t $REGISTRY_HOST/$REGISTRY_ORG/$APP_NAME:$HELM_REGISTRY_VERSION rootfs/grpc_server
    - docker push $REGISTRY_HOST/$REGISTRY_ORG/$APP_NAME:$HELM_REGISTRY_VERSION

helm_publish:
  stage: helm
  image: $HELM_REGISTRY_IMAGE
  only:
    - master
  dependencies: 
    - build_image
  script:
    - helm registry login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_HOST}
    - cd charts/grpc
    - helm registry push $REGISTRY_HOST/$REGISTRY_ORG/$REGISTRY_CHART_NAME -c beta
  
helm_lint:
  stage: helm
  image: $HELM_REGISTRY_IMAGE
  script:
    - cd charts/grpc
    - helm lint
